import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import ConvexClientProvider from "@/providers/convex-client-provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
					<ConvexClientProvider>
						{children}
						<Toaster />
					</ConvexClientProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
// "use client";

// import { Inter } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "@/providers/theme-provider";
// import ConvexClientProvider from "@/providers/convex-client-provider";
// import { Toaster } from "react-hot-toast";
// import { useEffect, useState, ReactNode } from 'react';

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({
//   children,
// }: {
//   children: ReactNode;
// }) {
//   const [isClient, setIsClient] = useState(false);

//   useEffect(() => {
//     setIsClient(true);
//   }, []);

//   return (
//     <html lang='en'>
//       <body className={isClient ? inter.className : ''}>
//         <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
//           <ConvexClientProvider>
//             {children}
//             <Toaster />
//           </ConvexClientProvider>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }